# Generated by Django 4.2.1 on 2025-05-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(upload_to='user_faces/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.voterlist')),
            ],
        ),
    ]
