# Generated by Django 4.2.1 on 2025-05-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimages',
            name='user',
        ),
    ]
